#!/bin/sh
#install tmux plugin manage

if [ ! -e $HOME/.tumx/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
fi
tmux source $HOME/.tmux.conf

#install vim plugin manage
if [ ! -e $HOME/.vim/bundle/vundle ]; then
  git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
fi
vim -u $HOME/.vimrc.bundles +BundleInstall +qa
